### ISSUE TITLE
feat: ClientProvider.cache as an interface to support external cache (e.g. redis)

### ISSUE THREAD

**Issue by c-nv-s** [TwiN/g8#8]
### Describe the feature request

At present it looks like the client provider cache field is tightly coupled to the gocache.
If a user wants to also use an external/shared/distributed cache then this isn't possible.
It would be nice to allow more flexibility to the user in which caching solution they wish to use.

### Why do you personally want this feature to be implemented?

to allow flexibility in choice of cache solution.

**Comment by c-nv-s** [comment]
@TwiN is this feature still a possibility?

**Comment by TwiN** [comment]
@c-nv-s I had started working on the side a bit a few months ago, but this isn't really a priority for me at the moment. 
Feel free to give a shot at implementing it yourself if you'd like.

**Comment by TwiN** [comment]
I've pushed the work I currently have and included the work left to do, in case you or somebody else wants to try it to confirm that it fits your need(s).

https://github.com/TwiN/g8/pull/12

**Comment by c-nv-s** [comment]
Thanks for this... so you just need to update the go.mod file then I can pull it and start using this?

**Comment by TwiN** [comment]
@c-nv-s You should be able to use the master branch as a version in your go.mod, see https://stackoverflow.com/questions/56408476/how-can-i-get-master-branch-of-a-dependency-when-using-go-modules 

I haven't had the opportunity to test it myself, hence why I haven't released it yet, but if you could give it a try, that'd be great.

**Comment by TwiN** [comment]
@c-nv-s I've just release it in v2.0.0
